# general settings
name: DTFL_TFL_Pred
model_type: EDCModel
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    name: DBM_128
    type: EDCDataset
    data_root:  E:\Desktop\Bathymetry_Data\data_vf\dataset_128\train_set\etopo
    mask_type: random  # random or irregular (which is strip-shaped in tha paper)
    data_aug: True
    training_mode: True
    image_size: [128,128]


    # data loader
    use_shuffle: true
    num_worker_per_gpu: 0
    batch_size_per_gpu: 12  # when training, set it to 64.
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: DBM_128
    type: EDCDataset2
    data_root:  E:\Desktop\Bathymetry_Data\data_vf\dataset_128\test_set\gt\etopo
    mask_root:  E:\Desktop\Bathymetry_Data\data_vf\dataset_128\test_set\mask\random
    data_aug: False
    training_mode: False
    image_size: [128,128]


# network structures
network_g:
  type:  Edge  # same as ETU.
  img_channels: 2
  dim: 32

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [ 0.9, 0.99 ]

  scheduler:
    type: MultiStepLR
    milestones: [50000]
    gamma: 0.5

  total_iter: 77000 # epoch : iteration = 1 : data_len/batch_size(128) = 1 : 193,
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0 #!!float 1e-2
    reduction: mean

  net_d_iters: 1
  net_d_init_iters: 0


# validation settings
val:
  val_freq: 385
  save_img: True
  pbar: True

  metrics:
    Precision:
      type: edge_precision
      better: higher

    Recall:
      type: edge_recall
      better: higher

    F1_score:
      type: edge_f1_score
      better: higher


# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
